# Generated by Django 4.1.7 on 2023-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
        migrations.AddField(
            model_name='reservation',
            name='full_name',
            field=models.TextField(default='John Doe', max_length=100),
        ),
    ]
