# Generated by Django 4.1.7 on 2023-03-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_id',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
