# Generated by Django 4.1.7 on 2023-03-26 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_reservation_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.IntegerField(choices=[(0, 'Family'), (1, 'Student'), (2, 'Couple')], default=0, max_length=1)),
                ('number_of_pass', models.IntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
