# Generated by Django 4.1.7 on 2023-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_groupbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbook',
            name='members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='groupbook',
            name='sub_pass_type',
            field=models.IntegerField(choices=[(0, 'Silver Pass'), (1, 'Blue Pass'), (2, 'Gold Pass')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='groupbook',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
