# Generated by Django 4.1.7 on 2023-03-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_ride'),
        ('home', '0013_groupbook_members_groupbook_sub_pass_type_and_more'),
    ]

    operations = [
    ]
